# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # encrypt only following comment in k3d.config.yaml, and MAC only encrypted keys
  - path_regex: k3d.config.yaml$
    encrypted_comment_regex: "sops_encrypt!"
    mac_only_encrypted: true
    age: age1wvg35rjqcqajvfk02dsegntfz0zuusn64xs4qk8pzugc7jqw538sh4597j
  # match all yaml files
  - path_regex: .yaml$
    encrypted_regex: ^(data|stringData)$
    age: age1wvg35rjqcqajvfk02dsegntfz0zuusn64xs4qk8pzugc7jqw538sh4597j
  # otherwise encrypt everything
  - age: age1wvg35rjqcqajvfk02dsegntfz0zuusn64xs4qk8pzugc7jqw538sh4597j
