# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # match all yaml files
  - path_regex: .yaml$
    encrypted_regex: ^(data|stringData)$
    age: age1wvg35rjqcqajvfk02dsegntfz0zuusn64xs4qk8pzugc7jqw538sh4597j
