---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 10m
  url: http://pajikos.github.io/home-assistant-helm-chart/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 10m
  chart:
    spec:
      chart: home-assistant
      version: 0.2.x
      sourceRef:
        kind: HelmRepository
        name: home-assistant
  releaseName: home-assistant
  values:
    service:
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "home-assistant"
    ingress:
      enabled: "true"
      hosts:
        - host: "ha.home.reub.in"
          paths:
            - path: /
              pathType: Prefix
    configuration:
      trusted_proxies: ["10.42.0.0/24"]
