---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 10m
  url: http://pajikos.github.io/home-assistant-helm-chart/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 10m
  chart:
    spec:
      chart: home-assistant
      version: 0.2.x
      sourceRef:
        kind: HelmRepository
        name: home-assistant
  releaseName: home-assistant
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: "ha.home.reub.in"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - ha.home.reub.in
          secretName: home-assistant-tls-cert
    configuration:
      enabled: true
      forceInit: true
      templateConfig: |-
        homekit:
          advertise_ip: 100.106.112.106
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: "local-path"
